# Generated by Django 3.0.5 on 2020-04-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grafos', '0003_auto_20200428_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafo',
            name='aristas_id',
        ),
        migrations.AddField(
            model_name='grafo',
            name='aristas_id',
            field=models.ManyToManyField(to='Grafos.Arista'),
        ),
        migrations.RemoveField(
            model_name='grafo',
            name='vertices_id',
        ),
        migrations.AddField(
            model_name='grafo',
            name='vertices_id',
            field=models.ManyToManyField(to='Grafos.Vertice'),
        ),
    ]
